SET FOREIGN_KEY_CHECKS=0;

-- 创建用户表

DROP TABLE IF EXISTS `SYS_USER`;
CREATE TABLE `SYS_USER` (
  `PK_ID` varchar(32) NOT NULL COMMENT '主键',
  `USER_NO` varchar(32) DEFAULT NULL COMMENT '用户账号',
  `USER_NAME` varchar(64) DEFAULT NULL COMMENT '用户姓名',
  `PASSWORD` varchar(32) DEFAULT NULL COMMENT '用户密码',
  `USER_SEX` varchar(1) DEFAULT NULL COMMENT '用户性别 0 男 1 女',
  `USER_AGE` varchar(3) DEFAULT NULL COMMENT '用户年龄',
  `USER_PHONE` varchar(11) DEFAULT NULL COMMENT '用户电话',
  `STATUS` varchar(1) DEFAULT NULL COMMENT '状态 0 正常 1 停用',
  `EMAIL` varchar(64) DEFAULT NULL COMMENT '邮箱',
  `NATION_CODE` varchar(2) DEFAULT NULL COMMENT '名族编码',
  `CREATE_TIME` varchar(19) DEFAULT NULL COMMENT '创建时间',
  `UPDATE_TIME` varchar(19) DEFAULT NULL COMMENT '更新时间',
  PRIMARY KEY (`PK_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='用户表';


SET FOREIGN_KEY_CHECKS=1;
