SET FOREIGN_KEY_CHECKS=0;

-- 创建名族表

DROP TABLE IF EXISTS `NATION`;
CREATE TABLE `NATION` (
  `NATION_CODE` varchar(4) NOT NULL COMMENT '名族编码',
  `NATION_NAME` varchar(64) DEFAULT NULL COMMENT '名族名称',
  PRIMARY KEY (`NATION_CODE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='名族表';

SET FOREIGN_KEY_CHECKS=1;