SET FOREIGN_KEY_CHECKS=0;

-- 创建角色表

DROP TABLE IF EXISTS `SYS_ROLE`;
CREATE TABLE `SYS_ROLE` (
  `PK_ID` varchar(32) NOT NULL COMMENT '主键',
  `ROLE_NAME` varchar(64) DEFAULT NULL COMMENT '角色名称',
  `ROLE_AUTHORITY` varchar(64) DEFAULT NULL COMMENT '角色授权key',
  `STATUS` varchar(1) DEFAULT NULL COMMENT '状态 0 正常 1 停用',
  `CREATE_TIME` varchar(19) DEFAULT NULL COMMENT '创建时间',
  `UPDATE_TIME` varchar(19) DEFAULT NULL COMMENT '更新时间',
  `SORT` varchar(4) DEFAULT NULL COMMENT '排序',
  PRIMARY KEY (`PK_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='角色表';


SET FOREIGN_KEY_CHECKS=1;
