SET FOREIGN_KEY_CHECKS=0;

-- 创建菜单表

DROP TABLE IF EXISTS `SYS_MENU`;
CREATE TABLE `SYS_MENU` (
  `PK_ID` varchar(32) NOT NULL COMMENT '主键',
  `PARENT_MENU_ID` varchar(32) NOT NULL COMMENT '父级菜单主键',
  `MENU_NAME` varchar(64) DEFAULT NULL COMMENT '菜单名称',
  `MENU_AUTHORITY` varchar(64) DEFAULT NULL COMMENT '菜单授权key',
  `MENU_IMG` varchar(64) DEFAULT NULL COMMENT '菜单图片',
  `STATUS` varchar(1) DEFAULT NULL COMMENT '状态 0 正常 1 停用',
  `CREATE_TIME` varchar(19) DEFAULT NULL COMMENT '创建时间',
  `UPDATE_TIME` varchar(19) DEFAULT NULL COMMENT '更新时间',
  `SORT` varchar(4) DEFAULT NULL COMMENT '排序',
  `TYPE` varchar(1) DEFAULT NULL COMMENT '类型 0 系统菜单 1 其他',
  PRIMARY KEY (`PK_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='菜单表';


SET FOREIGN_KEY_CHECKS=1;
