server:
  port: 8003

spring:
  # 环境 假设有 application-dev.yml 则使用 application-dev.yml
  profiles:
    active: dev
  # application 是项目名称  pom.xml 中的artifactId
  application:
    name: @pom.artifactId@
  # 数据源 mysql
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://127.0.0.1:3306/uxnux_auth?useUnicode=true&characterEncoding=utf8&serverTimezone=CST
    username: root
    password: root
    hikari:
      pool-name: hikariCP-biz
      auto-commit: false
      read-only: false
      maximum-pool-size: 20
      connection-timeout: 36000
      idle-timeout: 72000
      max-lifetime: 1800000

crypto:
  AES_KEY: 1234123412ABCDEF
  IV: 1234123412ABCDEF
  AES_TRANSFORMATION: AES/CBC/PKCS5Padding
  AES_ALGORITHM: AES
