spring:
  application:
    name: @pom.artifactId@

#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    type: com.zaxxer.hikari.HikariDataSource
#    url: jdbc:mysql://127.0.0.1:3306/uxnux-activiti?useUnicode=true&autoReconnect=true&characterEncoding=utf8&serverTimezone=CST
#    username: root
#    password: root
#    hikari:
#      pool-name: hikariCP-biz
#      auto-commit: false
#      read-only: false
#      maximum-pool-size: 20
#      max-lifetime: 1800000
#      connection-timeout: 30000
#      idle-timeout: 600000
  datasource:
    driver-class-name: dm.jdbc.driver.DmDriver
    type: org.apache.commons.dbcp.BasicDataSource
    url: jdbc:dm://127.0.0.1:5236/ACTIVITI_TEST
    username: SYSDBA
    password: Syp011500*

  # activiti 相关配置
  activiti:
    check-process-definitions: true #自动检查、部署流程定义  --
    database-schema-update: true #自动更新数据库结构 -- 在项目启动时检查数据库，进行建表等操作
    history-level: full #保存历史数据级别设置为full最高级别，便于历史数据的追溯
    process-definition-location-prefix: classpath:/processes/ #流程定义文件存放目录 默认：classpath:/processes/
#    process-definition-location-suffixes: 指定activiti流程描述文件的后缀/格式 默认：
#    - **.bpmn.xml
#    - **.bpmn20.xml



  #jpa相关配置
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true

# 端口
server:
  port: 8087

# 自定义activiti配置
activiti:
  database-type: oracle

