# 打包达梦数据库jdbcJar到本地仓库
# mvn install:install-file -DgroupId=com.dm -DartifactId=dm-jdbc-driver
# -Dversion=1.8.0 -Dpackaging=jar -Dfile=D:\达梦数据库\dmdbms\drivers\jdbc\DmJdbcDriver18.jar
spring:
  datasource:
    driver-class-name: dm.jdbc.driver.DmDriver
    url: jdbc:dm://127.0.0.1:5236/DEVELOPER?zeroDateTimeBehavior=convertToNull&useUnicode=true&characterEncoding=utf-8
    username: SYSDBA
    password: Syp011500*