
DROP TABLE IF EXISTS `LEAVE_PROCESS`;

create table LEAVE_PROCESS (
    LEAVE_PROCESS_ID VARCHAR(32) NOT NULL COMMENT '请假申请业务主键',
    LEAVE_USER_ID VARCHAR(32) NOT NULL COMMENT '请假用户主键',
    LEAVE_DAYS INTEGER NOT NULL COMMENT '请假天数',
    LEAVE_BEGIN_DATE DATE NOT NULL COMMENT '请假开始时间',
    LEAVE_END_DATE DATE NOT NULL COMMENT '请假结束时间',
    LEAVE_TYPE INTEGER(128) DEFAULT 2 COMMENT '请假类型：0:病假，1:事假，2:其他',
    LEAVE_REASON VARCHAR DEFAULT NULL COMMENT '请假内容',
    PROCESS_STATE INTEGER DEFAULT 0 COMMENT '状态：0:待审批，1:审批中，1:审批结束',
    CREATE_TIME DATETIME NOT NULL COMMENT '创建时间',
    UPDATE_TIME DATETIME NOT NULL COMMENT '更新时间',
    TASK_ID VARCHAR(32) NOT NULL COMMENT 'TASK_ID'
    primary key (LEAVE_PROCESS_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE utf8_bin COMMENT '申请表';

DROP TABLE IF EXISTS `LEAVE_APPROVAL`;

CREATE TABLE LEAVE_APPROVAL(
  LEAVE_APPROVAL_ID VARCHAR (32) NOT NULL COMMENT '请假审批主键',
  APPROVAL_USER_ID VARCHAR (32) NOT NULL COMMENT '审批用户ID',
  APPROVAL_RESULT INTEGER DEFAULT 0 COMMENT '状态：0:审批通过，1:审批不通过',
  APPROVAL_COMMENT VARCHAR(128) DEFAULT NULL COMMENT '审批内容',
  APPROVAL_TIME VARCHAR(19) DEFAULT NULL COMMENT '审批时间',
  TASK_ID VARCHAR(32) NOT NULL COMMENT '任务ID',
  PROCESS_INSTANCE_ID VARCHAR(32) NOT NULL COMMENT '流程id',
  PRIMARY KEY (LEAVE_APPROVAL_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE utf8_bin COMMENT '审批表';
